[phases.setup]
commands = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "pip install -r backend/requirements.txt"
]

[phases.build]
commands = [
  "flutter pub get --directory=frontend",
  "flutter build web --directory=frontend --dart-define=API_URL=https://your-backend-url"
]

[phases.start]
commands = [
  "uvicorn backend.app:app --host 0.0.0.0 --port 8000"
]